// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSF.DVDCentral.PL2.Data;

#nullable disable

namespace TSF.DVDCentral.PL2.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    partial class DVDCentralEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblCart");

                    b.HasData(
                        new
                        {
                            Id = new Guid("332e13a2-bf6b-41fe-bf60-b5d47e0e89fc"),
                            UserId = new Guid("d33e147e-8168-401c-b739-d837ba3f94d4")
                        },
                        new
                        {
                            Id = new Guid("32c46caa-b3af-4a58-b28a-686154ec91e6"),
                            UserId = new Guid("5cd9a2c2-a54b-4a67-a206-f080771e6c46")
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblCartItem");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db925cb9-1914-4a8a-860b-70bab18a41ff"),
                            CartId = new Guid("332e13a2-bf6b-41fe-bf60-b5d47e0e89fc"),
                            MovieId = new Guid("7c64848d-3fa5-48d4-87a1-495a57e94a76"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("0a5e9f29-aacb-4819-9680-55f8d41988dd"),
                            CartId = new Guid("332e13a2-bf6b-41fe-bf60-b5d47e0e89fc"),
                            MovieId = new Guid("97d65ba3-2789-46cc-81e4-64ddbb6a1a05"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("df56c3bf-f040-4d24-be71-8c441cf621ef"),
                            CartId = new Guid("32c46caa-b3af-4a58-b28a-686154ec91e6"),
                            MovieId = new Guid("97d65ba3-2789-46cc-81e4-64ddbb6a1a05"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZIP")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0486982-f906-44b1-84c1-62893dccda76"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("d33e147e-8168-401c-b739-d837ba3f94d4"),
                            ZIP = "54935"
                        },
                        new
                        {
                            Id = new Guid("e87eaf88-9ada-43b7-ac57-05d50f3a9f56"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("5cd9a2c2-a54b-4a67-a206-f080771e6c46"),
                            ZIP = "56495"
                        },
                        new
                        {
                            Id = new Guid("aedf3410-4d7c-4107-86c2-3304d2d0b8a6"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("7dcf4b54-921e-4cd2-a07d-0082264bf6bf"),
                            ZIP = "53142"
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4d54b8b-de88-4a1e-8ce1-8e6f3811eadd"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("68e368f2-817b-4250-ae7c-295baecf2872"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("55dd42ba-32eb-4b47-8a6c-04b43507c6db"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("cccb7073-fae5-4d73-b06b-37ac9eff399d"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("9c3c136a-8ca7-45be-89d2-48f435445bfb"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("d9ca0a80-d880-4c35-96d1-a7cfd8977826"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88af9351-8238-453e-98e9-9011daf02af5"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("c42b60e7-2e91-4146-a47b-41ffcc1f2f29"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("3f6b69f0-3019-4144-913a-52241ca9620f"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("5e7e8a54-f847-4682-8072-e605abcfbe6a"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c55427bb-6830-490d-a92d-f4a4e005caea"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("34589a40-c2af-497e-bc2c-df52ae3e5cd6"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("212836a7-cd81-434b-84b7-f537a97771d2"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("8da7c3bd-38a8-4af1-82c8-34b7f28801b3"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("7b5990bc-61b9-47ab-b9f3-e63f2477bd63"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("47c97388-2979-4577-88f1-7923a27606e8"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("cfc67b74-e3d4-4dd7-a2c2-3c56d429bb2c"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("bb2e4e35-f56d-43ee-8dca-ca3371e071f3"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("52f5e158-fe8c-43ea-b327-d5b655e46b63"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("bbbc2490-e3f5-4589-90a8-34fe4d75298f"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("RatingId");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c64848d-3fa5-48d4-87a1-495a57e94a76"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("d4d54b8b-de88-4a1e-8ce1-8e6f3811eadd"),
                            FormatId = new Guid("88af9351-8238-453e-98e9-9011daf02af5"),
                            ImagePath = "Rocky.jpg",
                            Quantity = 2,
                            RatingId = new Guid("83032d4c-fec2-4a90-b9e6-283ab967942f"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("eeb02716-7d4b-4ca8-a0a6-8da2f6453da8"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("d4d54b8b-de88-4a1e-8ce1-8e6f3811eadd"),
                            FormatId = new Guid("88af9351-8238-453e-98e9-9011daf02af5"),
                            ImagePath = "Rocky.jpg",
                            Quantity = 2,
                            RatingId = new Guid("83032d4c-fec2-4a90-b9e6-283ab967942f"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("97d65ba3-2789-46cc-81e4-64ddbb6a1a05"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("68e368f2-817b-4250-ae7c-295baecf2872"),
                            FormatId = new Guid("c42b60e7-2e91-4146-a47b-41ffcc1f2f29"),
                            ImagePath = "Jaws1.jpg",
                            Quantity = 1,
                            RatingId = new Guid("519cbe56-4714-4a3d-91ff-5bfac3ed301f"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("fc09c6c8-7f4f-4b90-89f3-100d67cba9e3"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("55dd42ba-32eb-4b47-8a6c-04b43507c6db"),
                            FormatId = new Guid("3f6b69f0-3019-4144-913a-52241ca9620f"),
                            ImagePath = "PrincessBride.jpg",
                            Quantity = 4,
                            RatingId = new Guid("d7a7ef3c-2dda-4963-94a9-a78220700e09"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("89140fae-2f4c-45b9-8b85-490b0b7c1f0b"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("cccb7073-fae5-4d73-b06b-37ac9eff399d"),
                            FormatId = new Guid("3f6b69f0-3019-4144-913a-52241ca9620f"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            Quantity = 2,
                            RatingId = new Guid("03d0de13-4f1b-460d-b4c8-c23e265e05fd"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("33f653cb-5308-4453-99be-eec4e8798dda"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("68e368f2-817b-4250-ae7c-295baecf2872"),
                            FormatId = new Guid("c42b60e7-2e91-4146-a47b-41ffcc1f2f29"),
                            ImagePath = "StarWarsNewHope.jpg",
                            Quantity = 1,
                            RatingId = new Guid("519cbe56-4714-4a3d-91ff-5bfac3ed301f"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("ebc4162c-a971-4e51-92ba-1f0419832ded"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("68e368f2-817b-4250-ae7c-295baecf2872"),
                            FormatId = new Guid("c42b60e7-2e91-4146-a47b-41ffcc1f2f29"),
                            ImagePath = "PaleRider.jpg",
                            Quantity = 1,
                            RatingId = new Guid("519cbe56-4714-4a3d-91ff-5bfac3ed301f"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd59e16b-aaee-4dbb-b114-5b768f8c6490"),
                            GenreId = new Guid("212836a7-cd81-434b-84b7-f537a97771d2"),
                            MovieId = new Guid("7c64848d-3fa5-48d4-87a1-495a57e94a76")
                        },
                        new
                        {
                            Id = new Guid("6de1c0ff-673f-4326-b6d4-756b38be0172"),
                            GenreId = new Guid("8da7c3bd-38a8-4af1-82c8-34b7f28801b3"),
                            MovieId = new Guid("7c64848d-3fa5-48d4-87a1-495a57e94a76")
                        },
                        new
                        {
                            Id = new Guid("357255a4-af64-48a7-8b1e-ce6fc9d94ae3"),
                            GenreId = new Guid("47c97388-2979-4577-88f1-7923a27606e8"),
                            MovieId = new Guid("7c64848d-3fa5-48d4-87a1-495a57e94a76")
                        },
                        new
                        {
                            Id = new Guid("4e72d4df-8ac0-466d-b03f-22569e9e1317"),
                            GenreId = new Guid("212836a7-cd81-434b-84b7-f537a97771d2"),
                            MovieId = new Guid("97d65ba3-2789-46cc-81e4-64ddbb6a1a05")
                        },
                        new
                        {
                            Id = new Guid("5f6ce3b2-c8b6-421e-bfe6-79f8cc64847c"),
                            GenreId = new Guid("8da7c3bd-38a8-4af1-82c8-34b7f28801b3"),
                            MovieId = new Guid("97d65ba3-2789-46cc-81e4-64ddbb6a1a05")
                        },
                        new
                        {
                            Id = new Guid("34f8a717-454c-42a4-ad9e-5fe5dac4242d"),
                            GenreId = new Guid("c55427bb-6830-490d-a92d-f4a4e005caea"),
                            MovieId = new Guid("fc09c6c8-7f4f-4b90-89f3-100d67cba9e3")
                        },
                        new
                        {
                            Id = new Guid("753aa70f-54c6-4e00-8267-220c75f9ae75"),
                            GenreId = new Guid("34589a40-c2af-497e-bc2c-df52ae3e5cd6"),
                            MovieId = new Guid("fc09c6c8-7f4f-4b90-89f3-100d67cba9e3")
                        },
                        new
                        {
                            Id = new Guid("968bfa58-7cf8-4864-98cb-adf8b058a755"),
                            GenreId = new Guid("47c97388-2979-4577-88f1-7923a27606e8"),
                            MovieId = new Guid("fc09c6c8-7f4f-4b90-89f3-100d67cba9e3")
                        },
                        new
                        {
                            Id = new Guid("00b91041-1311-4cfa-824c-b96f91888bcc"),
                            GenreId = new Guid("8da7c3bd-38a8-4af1-82c8-34b7f28801b3"),
                            MovieId = new Guid("89140fae-2f4c-45b9-8b85-490b0b7c1f0b")
                        },
                        new
                        {
                            Id = new Guid("3947b167-834b-4711-868d-3c01f4c15479"),
                            GenreId = new Guid("47c97388-2979-4577-88f1-7923a27606e8"),
                            MovieId = new Guid("89140fae-2f4c-45b9-8b85-490b0b7c1f0b")
                        },
                        new
                        {
                            Id = new Guid("a0c4c3a5-bb1d-4205-939b-90fbf0abd786"),
                            GenreId = new Guid("8da7c3bd-38a8-4af1-82c8-34b7f28801b3"),
                            MovieId = new Guid("33f653cb-5308-4453-99be-eec4e8798dda")
                        },
                        new
                        {
                            Id = new Guid("9198f64a-e42f-4a83-bc09-b69a825374ca"),
                            GenreId = new Guid("cfc67b74-e3d4-4dd7-a2c2-3c56d429bb2c"),
                            MovieId = new Guid("33f653cb-5308-4453-99be-eec4e8798dda")
                        },
                        new
                        {
                            Id = new Guid("4f95f91f-32c8-4925-9112-ce8c6fa585b4"),
                            GenreId = new Guid("bb2e4e35-f56d-43ee-8dca-ca3371e071f3"),
                            MovieId = new Guid("ebc4162c-a971-4e51-92ba-1f0419832ded")
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8c9499c-7112-4322-ad7a-499b6558c31e"),
                            CustomerId = new Guid("e87eaf88-9ada-43b7-ac57-05d50f3a9f56"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("5cd9a2c2-a54b-4a67-a206-f080771e6c46")
                        },
                        new
                        {
                            Id = new Guid("069f4810-7c80-4b04-b8cf-6ebd49bf3103"),
                            CustomerId = new Guid("aedf3410-4d7c-4107-86c2-3304d2d0b8a6"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("5cd9a2c2-a54b-4a67-a206-f080771e6c46")
                        },
                        new
                        {
                            Id = new Guid("585232c2-522d-4327-8c43-3bc0d98adfdb"),
                            CustomerId = new Guid("aedf3410-4d7c-4107-86c2-3304d2d0b8a6"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("7dcf4b54-921e-4cd2-a07d-0082264bf6bf")
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0847225b-17aa-4beb-980e-15f9a6c2adcf"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("7c64848d-3fa5-48d4-87a1-495a57e94a76"),
                            OrderId = new Guid("d8c9499c-7112-4322-ad7a-499b6558c31e"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("4e08b331-3c4b-462c-9c92-24b522c1c0d9"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("97d65ba3-2789-46cc-81e4-64ddbb6a1a05"),
                            OrderId = new Guid("d8c9499c-7112-4322-ad7a-499b6558c31e"),
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("f1bf0529-c3b3-46b6-8a5a-19694e220dd5"),
                            Cost = 10.99,
                            MovieId = new Guid("97d65ba3-2789-46cc-81e4-64ddbb6a1a05"),
                            OrderId = new Guid("069f4810-7c80-4b04-b8cf-6ebd49bf3103"),
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("83032d4c-fec2-4a90-b9e6-283ab967942f"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("519cbe56-4714-4a3d-91ff-5bfac3ed301f"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("d7a7ef3c-2dda-4963-94a9-a78220700e09"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("03d0de13-4f1b-460d-b4c8-c23e265e05fd"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("dd8f1343-c4f1-44e2-9066-8ad463f1e80f"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d33e147e-8168-401c-b739-d837ba3f94d4"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "smarin"
                        },
                        new
                        {
                            Id = new Guid("5cd9a2c2-a54b-4a67-a206-f080771e6c46"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("7dcf4b54-921e-4cd2-a07d-0082264bf6bf"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserName = "bfoote"
                        });
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblCart", b =>
                {
                    b.HasOne("TSF.DVDCentral.PL2.Entities.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblCartItem", b =>
                {
                    b.HasOne("TSF.DVDCentral.PL2.Entities.tblCart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TSF.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.HasOne("TSF.DVDCentral.PL2.Entities.tblDirector", "Director")
                        .WithMany("tblMovies")
                        .HasForeignKey("DirectorId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_DirectorId");

                    b.HasOne("TSF.DVDCentral.PL2.Entities.tblFormat", "Format")
                        .WithMany("tblMovies")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_FormatId");

                    b.HasOne("TSF.DVDCentral.PL2.Entities.tblRating", "Rating")
                        .WithMany("tblMovies")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("fk_tblMovie_RatingId");

                    b.Navigation("Director");

                    b.Navigation("Format");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblMovieGenre", b =>
                {
                    b.HasOne("TSF.DVDCentral.PL2.Entities.tblGenre", "Genre")
                        .WithMany("tblMovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_GenreId");

                    b.HasOne("TSF.DVDCentral.PL2.Entities.tblMovie", "Movie")
                        .WithMany("tblMovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblDirector", b =>
                {
                    b.Navigation("tblMovies");
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblFormat", b =>
                {
                    b.Navigation("tblMovies");
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblGenre", b =>
                {
                    b.Navigation("tblMovieGenres");
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblMovie", b =>
                {
                    b.Navigation("tblMovieGenres");
                });

            modelBuilder.Entity("TSF.DVDCentral.PL2.Entities.tblRating", b =>
                {
                    b.Navigation("tblMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
